apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: {{ .Values.jenkins.image }}
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-config
          mountPath: /var/jenkins_home/jenkins.yaml
          subPath: jenkins.yaml
      imagePullSecrets:
      - name: ecr-credentials
      volumes:
      - name: jenkins-home
        emptyDir: {}
      - name: jenkins-config
        configMap:
          name: jenkins-config

